### ISSUE TITLE
Feature request: Region information and more

### ISSUE THREAD

**Issue by lookye** [garoxas/NX_Game_Info#18]
**Describe the solution you'd like**
Add an information tab about the region similar to what Switch Backup Manager shows like EU,US, JP etc.

Is it also possible to export the loaded files as csv file or use ; instead of | to make a break between the columns in the exported txt?

**Additional context**

**Comment by garoxas** [comment]
SBM has region info? just popped the app but don't think it has one
maybe you meant language? that can be easily added since the language date is inside the NACP but not region (it maybe available from Nintendo server but it's too troublesome to regularly update the data)

regarding export feature, that's easy. but shouldn't it be commas instead of semi-colon for csv?

**Comment by lookye** [comment]
You´re right. Its the languages that are shown (region is only shown in "scene releases" in SBM). Anyway, showing the languages would be nice too (instead of Region).

For the csv: commas and semicolon are fine. I use semi-colon for csv files. Also some developer have a comma in its name and this would lead to errors. So using a semi-colon would be the nicer way imo.

**Comment by garoxas** [comment]
Export to csv will now use comma by default, but you can choose to use other separator by editing `user.settings` and modify the `CsvSeparator` value
