### ISSUE TITLE
Title Database & Update Database no longer working

### ISSUE THREAD

**Issue by Elionna** [garoxas/NX_Game_Info#25]
I think you were getting them from blawars repo which was taken down, you can get latest versions here
 
https://tinfoil.media/repo/db/titles.json
https://tinfoil.media/repo/db/versions.json

**Comment by garoxas** [comment]
no, I'm not using his database
what title and which updates that you're looking for?

**Comment by Elionna** [comment]
I used update version list but it's saying "0 titled have updated version"

For example for Killer Queen Black [0100F2900B3E2000]  327680 should be the latest version but the app is showing 262144

everything was working fine until a couple of months ago

**Comment by garoxas** [comment]
there's are some missing updates in the source that I'm using
it should be fixed in the next database update, so please try it again later. I believe the database is updated every sunday or maybe monday, and please report back if it still not solved by then

FWIW there's an alternative but it requires manual process
Reswitched discord also has the always updated hac_versionlist.json and is compatible with this app. you can download the file and put it on the same location as the app
unfortunately I cannot implement this in the app to automate the whole process

**Comment by Elionna** [comment]
ok, I'll report again in a week if the issue isn't fixed, thank you for you help and building this great app

**Comment by garoxas** [comment]
thank you 😃

**Comment by Elionna** [comment]
reporting in, it looks like it's working, the update list just seems to be delayed by a week
