### ISSUE TITLE
NSC support?

### ISSUE THREAD

**Issue by jakemelon** [garoxas/NX_Game_Info#26]
NSZ saves alot of space and is almost identical to NSP. In fact your tool already reads NSC files except that it is unable to validate the signature and provide permissions flag. Please add full NSC support as soon as possible. Keep up the awesome job!

**Comment by garoxas** [comment]
did you mean NSZ? if so then please see #19 
the only reason this app can show some information from compressed NCA because few hundred/thousand bytes in the header kept intact

**Comment by jakemelon** [comment]
Yes, that is what I meant, NSZ (sorry for the typo). Could you please add the signature validation and permission functionality to NSZ?

**Comment by garoxas** [comment]
I'm not sure about that, because I've tried adding NSZip support once (NSZ predecessor) and apparently decompressing everything on the fly cost too much RAM (decompress to HDD is not an option because it'll be too slow)
see this post for more detail https://gbatemp.net/threads/nx-game-info-for-macos-and-windows.528419/page-2#post-8545553
that's why I'm hesitant to put some effort to add NSZ support if I'll end up facing the same issue

_**"maybe"**_ some time in future, but I'll close this issue for now due to I don't see working on it soon. very sorry about that
