### ISSUE TITLE
DLC info missing

### ISSUE THREAD

**Issue by nbalonso** [garoxas/NX_Game_Info#9]
The DLC files are missing the title name, display version, latest version and permission

**Comment by garoxas** [comment]
All those information are not available in the DLC NSP

You can only have the Title name and Latest version shown in the app if you provide them manually in `title.keys` (see the 3rd format in https://github.com/garoxas/LibHac/blob/NX_Game_Info/KEYS.md#title-keys in the `title_name` and `version` column)

Display version and Permission are not applicable for DLC

**Comment by garoxas** [comment]
Here's a more detailed technical stuff why this doesn't work

`Title Name` and `Display Version` are retrieved from [control.nacp](https://switchbrew.org/wiki/NACP_Format) file which does not exist in DLC NSP, so the only way to retrieve that information to get it directly from Nintendo server which is not supported by this app right now because it requires console certificates and might risk on getting banned if improperly implemented
`Display Version` itself is irrelevant for DLC as it only refers to the usual version numbering to track the version changes (e.g. v65536) and not display version (e.g. 1.0.1)

`Latest Version` is not available from [tagaya](https://switchbrew.org/wiki/Network#tagaya) server, although it's available on other Nintendo servers as mentioned above but the same issue applies that's why it's not implemented and can only be forced by putting them manually in the external `title.keys` for the app to use

`Permission` is only applicable for executable files while DLC does not have them, there are only data files in the DLC
